# ============================================================
# NSO GAME SERVER - CAU HINH HE THONG VA CLOUD VM
# ============================================================

VM_IP=134.185.83.12
VM_USER=ubuntu
VM_PORT=14444
SSH_KEY=config/ssh-key-2026-10-08.key
WEB_PORT=4000
SERVER_PROFILE=STANDARD
